# Generated by Django 4.1.7 on 2023-02-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WBCImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('slide', models.IntegerField()),
                ('src', models.CharField(max_length=50)),
                ('imgID', models.IntegerField()),
            ],
        ),
    ]
