# Generated by Django 4.1.7 on 2023-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0002_morphologyconfig_wbcdiffconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('morphology', models.TextField()),
            ],
        ),
    ]
