# Generated by Django 4.1.7 on 2023-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0005_wbcimg_lat_wbcimg_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbcdiffconfig',
            name='key_bind',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
