# Generated by Django 4.1.7 on 2023-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0006_wbcdiffconfig_key_bind'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbcimg',
            name='lat_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbcimg',
            name='lat_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbcimg',
            name='lng_lower',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbcimg',
            name='lng_upper',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
