# Generated by Django 4.1.7 on 2023-04-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0008_slide_coordinate_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbcdiffconfig',
            name='key_bind',
            field=models.IntegerField(null=True),
        ),
    ]
