# Generated by Django 4.1.7 on 2023-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0009_alter_wbcdiffconfig_key_bind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroscopeUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('in_use', models.BooleanField()),
            ],
        ),
    ]
