# Generated by Django 4.1.7 on 2023-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide_analyzer', '0010_microscopeuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscopeuse',
            name='current_field',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microscopeuse',
            name='current_wbc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microscopeuse',
            name='slide',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microscopeuse',
            name='target_field',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microscopeuse',
            name='target_wbc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
